pipeline {
    agent any
    tools {
         maven 'apache-maven-3.6.0' 
    }
    stages {
      stage('----clean-----'){
          steps {
	     sh "mvn clean"
	  }
      }
      stage('---test--'){
         steps{
           sh "mvn test"
         }
      }
      stage('---package--'){
         steps{
           sh "mvn package"
         }
      }
	 
    }
}
